export const SITE_URL = "https://www.tinybundle.app";

export const ogImageSize = {
  width: 1200,
  height: 630,
} as const;

export const layersOgImage = {
  url: "/tinylayers/og-social.png",
  width: ogImageSize.width,
  height: ogImageSize.height,
  alt: "TinyLayers baby outfit guidance for sleep, naps, and going out",
} as const;

export const bundleOgImage = {
  url: "/og-social.png",
  width: ogImageSize.width,
  height: ogImageSize.height,
  alt: "TinyBundle - Four moments. One journey. We've got you.",
} as const;

export const havenOgImage = {
  url: "/tinyhaven/og-social.png",
  width: ogImageSize.width,
  height: ogImageSize.height,
  alt: "TinyHaven - You're not the only one awake. Late-night companion for parents.",
} as const;

/** File-based OG routes generated by Next.js (`opengraph-image.tsx`). */
export function routeOgImage(path: string, alt: string) {
  const base = path === "/" ? "" : path.replace(/\/$/, "");
  return {
    url: `${base}/opengraph-image`,
    width: ogImageSize.width,
    height: ogImageSize.height,
    alt,
  } as const;
}

export const bloomsOgImage = routeOgImage(
  "/tinyblooms",
  "TinyBlooms - One lovely thing to do with baby. Age-based ideas, coming soon.",
);

export const mealsOgImage = routeOgImage(
  "/tinymeals",
  "TinyMeals - Something good from what you have. Baby-friendly meals, coming soon.",
);

export function absoluteUrl(path: string) {
  if (path.startsWith("http")) return path;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}
